# Audio and Video Feature Fusion

## OpenFace Files

In [ ]:
 Since the files generated through openface .csv we convert the audio.npy file to .csv

In [8]:
import numpy as np

# Load the data from the Numpy binary file
MediaPipe_audio = np.load('trial_lie_001_000_audio.npy')

# Save the data as a CSV file
np.savetxt('trial_lie_001_000_audio.csv', MediaPipe_audio, delimiter=',')
MediaPipe_audio
print("Shape:", MediaPipe_audio.shape)

[[ 0.          0.        ]
 [ 0.          0.        ]
 [ 0.          0.        ]
 ...
 [-0.00698853  0.00115967]
 [-0.00628662  0.0010376 ]
 [-0.00579834  0.00094604]]
Shape: (185661, 2)

In [67]:
#read into a dataframe
MediaPipe_audio= pd.read_csv('trial_lie_001_000_audio.csv')
MediaPipe_audio

        0.000000000000000000e+00  0.000000000000000000e+00.1
0                       0.000000                    0.000000
1                       0.000000                    0.000000
2                       0.000000                    0.000000
3                       0.000000                    0.000000
4                       0.000000                    0.000000
...                          ...                         ...
185655                 -0.007294                    0.000916
185656                 -0.007233                    0.001190
185657                 -0.006989                    0.001160
185658                 -0.006287                    0.001038
185659                 -0.005798                    0.000946

[185660 rows x 2 columns]

In [11]:
#Read the .csv file generated after passing one file through OpenFace.
import pandas as pd
OpenFace_video = pd.read_csv('trial_lie_001_000_openface.csv')

# Display the data
# print(OpenFace_video)

OpenFace_video.head()

,FaceRectX,FaceRectY,FaceRectWidth,FaceRectHeight,FaceScore,x_0,x_1,x_2,x_3,x_4,...,AU43,anger,disgust,fear,happiness,sadness,surprise,neutral,input,frame
0,407.422024,112.832275,98.081231,125.438125,0.989365,412.103813,411.727582,413.331898,417.740588,423.143773,...,0.201936,0.008858,0.000931,0.004510,0.846660,0.024106,0.105119,0.009816,C:\Work\606Capstone\Video_chunks\Sample\trial_...,0
1,407.379583,112.840490,98.065050,125.461160,0.989362,412.170298,411.798642,413.402133,417.798531,423.190174,...,0.261847,0.008501,0.000901,0.004469,0.847686,0.024718,0.104270,0.009456,C:\Work\606Capstone\Video_chunks\Sample\trial_...,1
2,407.730491,113.668805,98.572132,125.491949,0.987956,412.787646,412.444740,414.060805,418.357487,423.681083,...,0.160625,0.003950,0.000772,0.004099,0.845811,0.032173,0.104306,0.008888,C:\Work\606Capstone\Video_chunks\Sample\trial_...,2
3,407.656019,113.863420,98.482440,125.406488,0.987745,413.093359,412.650282,414.318238,418.867562,424.493420,...,0.051434,0.005017,0.000726,0.003419,0.596768,0.058433,0.293819,0.041819,C:\Work\606Capstone\Video_chunks\Sample\trial_...,3
4,408.283298,114.822023,98.516228,124.739104,0.986979,413.305362,412.989890,414.624331,418.996396,424.495993,...,0.041384,0.004569,0.000539,0.002373,0.702102,0.064553,0.196238,0.029626,C:\Work\606Capstone\Video_chunks\Sample\trial_...,4

In [57]:
#just consodering the AUs and the x and y coordinates from the extraction.
OpenFace_video_new = OpenFace_video.drop(['FaceRectX', 'FaceRectY','FaceRectWidth','FaceRectHeight','FaceScore','input','frame'], axis=1)
OpenFace_video_new.head()

,x_0,x_1,x_2,x_3,x_4,x_5,x_6,x_7,x_8,x_9,...,AU26,AU28,AU43,anger,disgust,fear,happiness,sadness,surprise,neutral
0,412.103813,411.727582,413.331898,417.740588,423.143773,429.554699,436.464807,443.516875,453.775099,466.588792,...,0.104904,0.056654,0.201936,0.008858,0.000931,0.004510,0.846660,0.024106,0.105119,0.009816
1,412.170298,411.798642,413.402133,417.798531,423.190174,429.590953,436.498314,443.567848,453.846854,466.682010,...,0.321481,0.021233,0.261847,0.008501,0.000901,0.004469,0.847686,0.024718,0.104270,0.009456
2,412.787646,412.444740,414.060805,418.357487,423.681083,430.061249,437.112986,444.450951,454.866283,467.647969,...,0.137118,0.101169,0.160625,0.003950,0.000772,0.004099,0.845811,0.032173,0.104306,0.008888
3,413.093359,412.650282,414.318238,418.867562,424.493420,431.101621,438.292503,445.822482,456.477453,469.369014,...,0.157042,0.067265,0.051434,0.005017,0.000726,0.003419,0.596768,0.058433,0.293819,0.041819
4,413.305362,412.989890,414.624331,418.996396,424.495993,431.168467,438.632031,446.521475,457.353652,470.183009,...,0.184572,0.095815,0.041384,0.004569,0.000539,0.002373,0.702102,0.064553,0.196238,0.029626

In [58]:
#changing the datatype for columns to float.
OpenFace_video_new['AU20'] = OpenFace_video_new['AU20'].astype(float)
OpenFace_video_new['AU07'] = OpenFace_video_new['AU07'].astype(float)
OpenFace_video_new

,x_0,x_1,x_2,x_3,x_4,x_5,x_6,x_7,x_8,x_9,...,AU26,AU28,AU43,anger,disgust,fear,happiness,sadness,surprise,neutral
0,412.103813,411.727582,413.331898,417.740588,423.143773,429.554699,436.464807,443.516875,453.775099,466.588792,...,0.104904,0.056654,0.201936,0.008858,0.000931,0.004510,0.846660,0.024106,0.105119,0.009816
1,412.170298,411.798642,413.402133,417.798531,423.190174,429.590953,436.498314,443.567848,453.846854,466.682010,...,0.321481,0.021233,0.261847,0.008501,0.000901,0.004469,0.847686,0.024718,0.104270,0.009456
2,412.787646,412.444740,414.060805,418.357487,423.681083,430.061249,437.112986,444.450951,454.866283,467.647969,...,0.137118,0.101169,0.160625,0.003950,0.000772,0.004099,0.845811,0.032173,0.104306,0.008888
3,413.093359,412.650282,414.318238,418.867562,424.493420,431.101621,438.292503,445.822482,456.477453,469.369014,...,0.157042,0.067265,0.051434,0.005017,0.000726,0.003419,0.596768,0.058433,0.293819,0.041819
4,413.305362,412.989890,414.624331,418.996396,424.495993,431.168467,438.632031,446.521475,457.353652,470.183009,...,0.184572,0.095815,0.041384,0.004569,0.000539,0.002373,0.702102,0.064553,0.196238,0.029626
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121,420.577943,421.513688,424.250510,429.159378,434.607440,440.864614,448.049061,456.095026,467.147528,480.244417,...,0.200522,0.038472,0.077678,0.002994,0.000276,0.001016,0.821489,0.016751,0.103983,0.053490
122,422.836886,424.065864,427.009339,431.877310,437.338460,443.766450,451.147305,459.733019,471.233105,484.536275,...,0.154261,0.077584,0.073863,0.003331,0.000586,0.004963,0.086133,0.120263,0.673898,0.110825
123,421.841451,423.401972,426.580875,431.756535,437.517217,444.360076,452.316246,461.420811,473.130681,486.362123,...,0.119358,0.164719,0.031887,0.001989,0.000395,0.003517,0.148902,0.143657,0.645058,0.056482
124,424.313800,426.045167,429.608968,434.983333,440.787529,447.560481,455.580181,464.973767,476.785743,490.211653,...,0.123970,0.158698,0.076016,0.000709,0.000174,0.000851,0.061199,0.020776,0.886683,0.029608
125,423.932816,425.904905,429.705895,435.472454,441.759244,448.882590,457.110806,466.552603,478.375647,491.757168,...,0.185279,0.071205,0.066442,0.002905,0.000460,0.002805,0.110757,0.178537,0.633527,0.071008

In [65]:
MediaPipe_audio

array([[ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       ...,
       [-0.00698853,  0.00115967],
       [-0.00628662,  0.0010376 ],
       [-0.00579834,  0.00094604]])

In [48]:
#checking for null values
# null_count = OpenFace_video_new.isnull().sum()
# print(null_count)

x_0          0
x_1          0
x_2          0
x_3          0
x_4          0
            ..
happiness    0
sadness      0
surprise     0
neutral      0
frame        0
Length: 167, dtype: int64

In [52]:
# OpenFace_video_1 = OpenFace_video_new.dropna()
# null_count = OpenFace_video_1.isnull().sum()
# print(null_count)

In [59]:
OpenFace_video_new.to_csv('trial_lie_001_000_Openface_filtered.csv', index=False)

In [31]:
# 
# OpenFace_Final = np.genfromtxt('trial_lie_001_000_Openface_filtered.csv', delimiter=',')

# # Save the data as a Numpy binary file
# np.save('trial_lie_001_000_Openface_filtered.npy', OpenFace_Final)
# print( OpenFace_Final)

[[           nan            nan            nan ...            nan
             nan            nan]
 [4.12103813e+02 4.11727582e+02 4.13331898e+02 ... 2.41063600e-02
  1.05119030e-01 9.81633800e-03]
 [4.12170298e+02 4.11798642e+02 4.13402133e+02 ... 2.47178880e-02
  1.04269795e-01 9.45593000e-03]
 ...
 [4.21841451e+02 4.23401972e+02 4.26580875e+02 ... 1.43657150e-01
  6.45058200e-01 5.64815660e-02]
 [4.24313800e+02 4.26045167e+02 4.29608968e+02 ... 2.07763280e-02
  8.86683300e-01 2.96083840e-02]
 [4.23932816e+02 4.25904905e+02 4.29705895e+02 ... 1.78536600e-01
  6.33527200e-01 7.10082700e-02]]

### Method 1 - Concatenation

In [75]:
#concatinating the dataframes
display(pd.concat([OpenFace_video_new, MediaPipe_audio], axis = 1))

,x_0,x_1,x_2,x_3,x_4,x_5,x_6,x_7,x_8,x_9,...,AU43,anger,disgust,fear,happiness,sadness,surprise,neutral,0.000000000000000000e+00,0.000000000000000000e+00.1
0,412.103813,411.727582,413.331898,417.740588,423.143773,429.554699,436.464807,443.516875,453.775099,466.588792,...,0.201936,0.008858,0.000931,0.004510,0.846660,0.024106,0.105119,0.009816,0.000000,0.000000
1,412.170298,411.798642,413.402133,417.798531,423.190174,429.590953,436.498314,443.567848,453.846854,466.682010,...,0.261847,0.008501,0.000901,0.004469,0.847686,0.024718,0.104270,0.009456,0.000000,0.000000
2,412.787646,412.444740,414.060805,418.357487,423.681083,430.061249,437.112986,444.450951,454.866283,467.647969,...,0.160625,0.003950,0.000772,0.004099,0.845811,0.032173,0.104306,0.008888,0.000000,0.000000
3,413.093359,412.650282,414.318238,418.867562,424.493420,431.101621,438.292503,445.822482,456.477453,469.369014,...,0.051434,0.005017,0.000726,0.003419,0.596768,0.058433,0.293819,0.041819,0.000000,0.000000
4,413.305362,412.989890,414.624331,418.996396,424.495993,431.168467,438.632031,446.521475,457.353652,470.183009,...,0.041384,0.004569,0.000539,0.002373,0.702102,0.064553,0.196238,0.029626,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185655,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.007294,0.000916
185656,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.007233,0.001190
185657,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.006989,0.001160
185658,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.006287,0.001038
185659,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.005798,0.000946

In [70]:
#concatinating using the .csv files
from sklearn.preprocessing import MinMaxScaler

# Load the two DataFrames to be concatenated
df1 = pd.read_csv('trial_lie_001_000_audio.csv')
df2 = pd.read_csv('trial_lie_001_000_Openface_filtered.csv')

# Normalize the values in each DataFrame using MinMaxScaler
scaler = MinMaxScaler()
df1_norm = pd.DataFrame(scaler.fit_transform(df1), columns=df1.columns)
df2_norm = pd.DataFrame(scaler.fit_transform(df2), columns=df2.columns)

# Concatenate the normalized DataFrames vertically
concatenated_df_1 = pd.concat([df1_norm, df2_norm], ignore_index=True)

# Print the concatenated DataFrame
concatenated_df_1

,0.000000000000000000e+00,0.000000000000000000e+00.1,x_0,x_1,x_2,x_3,x_4,x_5,x_6,x_7,...,AU26,AU28,AU43,anger,disgust,fear,happiness,sadness,surprise,neutral
0,0.607238,0.359223,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.607238,0.359223,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.607238,0.359223,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0.607238,0.359223,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.607238,0.359223,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185781,NaN,NaN,0.486103,0.562777,0.632110,0.667781,0.692031,0.714626,0.733164,0.725455,...,0.245499,0.042621,0.130835,0.007897,0.002362,0.001106,0.925357,0.012108,0.079053,0.207689
185782,NaN,NaN,0.556273,0.644820,0.722413,0.755311,0.777616,0.803464,0.824397,0.820964,...,0.126723,0.126881,0.122280,0.009061,0.009510,0.027528,0.087833,0.163405,0.711129,0.474666
185783,NaN,NaN,0.525352,0.623478,0.708388,0.751422,0.783217,0.821637,0.858818,0.865274,...,0.037112,0.314600,0.028141,0.004424,0.005110,0.017846,0.159323,0.197599,0.679144,0.221617
185784,NaN,NaN,0.602151,0.708447,0.807505,0.855340,0.885702,0.919615,0.954929,0.958551,...,0.048953,0.301628,0.127109,0.000000,0.000000,0.000000,0.059434,0.017990,0.947124,0.096483
185785,NaN,NaN,0.590317,0.703938,0.810678,0.871092,0.916154,0.960090,1.000000,1.000000,...,0.206364,0.113139,0.105636,0.007588,0.006604,0.013085,0.115878,0.248580,0.666355,0.289260

In [68]:
from sklearn.preprocessing import MinMaxScaler

# Load the audio and video CSV files into memory
audio_df = pd.read_csv('trial_lie_001_000_audio.csv')
video_df = pd.read_csv('trial_lie_001_000_Openface_filtered.csv')

# Check that the audio and video CSV files have a common identifier
# if 'timestamp' not in audio_df.columns or 'timestamp' not in video_df.columns:
#     raise ValueError("Both CSV files must have a 'timestamp' column")

# scaler = MinMaxScaler()
# audio_df.iloc[:, 1:] = scaler.fit_transform(audio_df.iloc[:, 1:])
# video_df.iloc[:, 1:] = scaler.fit_transform(video_df.iloc[:, 1:])

# Concatenate the two CSV files
concatenated_df = pd.concat([audio_df, video_df], axis=1)

# Merge the two CSV files based on the common identifier
# merged_df = pd.merge(audio_df, video_df, on='timestamp')

# Save the concatenated and merged CSV file to a new file
concatenated_df.to_csv('concatenated.csv', index=False)
# merged_df.to_csv('merged.csv', index=False)

concatenated_df

,0.000000000000000000e+00,0.000000000000000000e+00.1,x_0,x_1,x_2,x_3,x_4,x_5,x_6,x_7,...,AU26,AU28,AU43,anger,disgust,fear,happiness,sadness,surprise,neutral
0,0.000000,0.000000,412.103813,411.727582,413.331898,417.740588,423.143773,429.554699,436.464807,443.516875,...,0.104904,0.056654,0.201936,0.008858,0.000931,0.004510,0.846660,0.024106,0.105119,0.009816
1,0.000000,0.000000,412.170298,411.798642,413.402133,417.798531,423.190174,429.590953,436.498314,443.567848,...,0.321481,0.021233,0.261847,0.008501,0.000901,0.004469,0.847686,0.024718,0.104270,0.009456
2,0.000000,0.000000,412.787646,412.444740,414.060805,418.357487,423.681083,430.061249,437.112986,444.450951,...,0.137118,0.101169,0.160625,0.003950,0.000772,0.004099,0.845811,0.032173,0.104306,0.008888
3,0.000000,0.000000,413.093359,412.650282,414.318238,418.867562,424.493420,431.101621,438.292503,445.822482,...,0.157042,0.067265,0.051434,0.005017,0.000726,0.003419,0.596768,0.058433,0.293819,0.041819
4,0.000000,0.000000,413.305362,412.989890,414.624331,418.996396,424.495993,431.168467,438.632031,446.521475,...,0.184572,0.095815,0.041384,0.004569,0.000539,0.002373,0.702102,0.064553,0.196238,0.029626
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185655,-0.007294,0.000916,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
185656,-0.007233,0.001190,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
185657,-0.006989,0.001160,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
185658,-0.006287,0.001038,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
185659,-0.005798,0.000946,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Method 2 - PCA

In [63]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
# Load the audio and video CSV files into memory
audio_df = pd.read_csv('trial_lie_001_000_audio.csv')
video_df = pd.read_csv('trial_lie_001_000_Openface_filtered.csv')

# # Merge the audio and visual feature files based on the frame ID
# merged_features = pd.merge(audio_df, video_df, on='frame')

# audio_selected = merged_features.iloc[:, 1:11] # Change the column range to match your audio features
# visual_selected = merged_features.iloc[:, 11:] # Change the column range to match your visual features

# Apply PCA to reduce the dimensionality of the features
pca = PCA(n_components)
audio_pca = pca.fit_transform(audio_df)
visual_pca = pca.fit_transform(visual_df)

# Concatenate the PCA features
fused_features = np.concatenate((audio_pca, visual_pca), axis=1)

# Save the fused feature file
# fused_df = pd.DataFrame(fused_features, columns=['PC1', 'PC2', 'PC3'])
# fused_df.to_csv('fused_features.csv', index=False)

NameError: name 'n_components' is not defined

In [30]:
# # Load audio and video features from .csv files
# audio_feature = pd.read_csv("trial_lie_001_000_audio.npy")
# video_feature = pd.read_csv("trial_lie_001_000_Openface_filtered.npy")

# # Normalize audio and video features
# audio_norm = (audio_feature - np.mean(audio_feature)) / np.std(audio_feature)
# video_norm = (video_feature - np.mean(video_feature)) / np.std(video_feature)

# # Concatenate normalized audio and video features
# fused_feature = np.concatenate((audio_norm.flatten(), video_norm.flatten()))
# print(fused_feature)

# # Save the fused feature as a .csv file
# #np.savetxt("fused_feature_concatenation_OpenFace.csv", fused_feature, delimiter=",")

# # Use the fused feature for further processing or modeling
# print("Shape of fused feature:", fused_feature.shape)

ParserError: Error tokenizing data. C error: Expected 618 fields in line 70, saw 1104